# Generated by Django 2.2.3 on 2019-07-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_api', '0005_auto_20190720_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_db',
            name='type',
            field=models.CharField(choices=[('LE', 'Lecture'), ('LA', 'Lab'), ('TU', 'Tutorial')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
