# Generated by Django 2.2.3 on 2019-11-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_api', '0006_section_db_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_db',
            name='formatted_time',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
