# Generated by Django 2.2.3 on 2019-11-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic_api', '0007_section_db_formatted_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section_db',
            old_name='formatted_time',
            new_name='formated_time',
        ),
    ]
