# Generated by Django 2.2.1 on 2019-05-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.IntegerField(default=201905),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='term',
            field=models.IntegerField(default=201905),
            preserve_default=False,
        ),
    ]
