# Generated by Django 2.2.1 on 2019-05-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableBuilder', '0002_auto_20190512_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='Sections',
        ),
    ]
